In [1]:
import pandas as pd
from bokeh.models import ColumnDataSource, Panel, Tabs
from bokeh.plotting import figure, show
from bokeh.transform import dodge

In [11]:
# Read the CSV file - All of data combined
Main_data_df = pd.read_csv("Resources/Analysis_complete.csv")

Main_data_df=pd.DataFrame(Main_data_df)

# Display the first few rows
Main_data_df.head()

,AirlineName,CarrierCode,Month,DayOfWeek,TravelType,CabinType,Avg_OverallScore,Avg_SeatComfortRating,Avg_EntertainmentRating,Avg_FoodRating,Avg_GroundServiceRating,Avg_ServiceRating,Avg_ValueRating,Avg_WifiRating,Avg_DepartureDelay,CancelRate,Avg_AirTime,Avg_Distance,OriginAirport
0,Southwest Airlines,WN,9,Tuesday,Couple Leisure,Economy Class,9.0,4.0,0.0,3.0,4.0,5.0,5.0,0.0,57.000000,0.0,180.5,1428.000000,LGA
1,Southwest Airlines,WN,9,Monday,Family Leisure,Economy Class,1.0,3.0,0.0,0.0,1.0,4.0,1.0,0.0,16.750000,0.0,115.5,848.750000,MDW
2,American Airlines,AA,6,Friday,Family Leisure,First Class,2.0,3.0,0.0,4.0,3.0,3.0,3.0,0.0,-1.000000,0.0,129.0,931.000000,GRR
3,Southwest Airlines,WN,5,Sunday,Solo Leisure,Economy Class,3.0,1.0,1.0,1.0,1.0,4.0,1.0,1.0,31.666667,0.0,94.0,652.333333,SLC
4,Southwest Airlines,WN,7,Wednesday,Business,Economy Class,3.0,1.0,0.0,1.0,2.0,2.0,3.0,1.0,0.000000,0.0,180.0,1211.000000,OMA

In [3]:
columns_to_keep = {
    'AirlineName':'Airline',
    'Avg_OverallScore':'Overall',
    'Avg_SeatComfortRating':'Comfort',
    'Avg_EntertainmentRating':'Entertainment',
    'Avg_FoodRating':'Food',
    'Avg_GroundServiceRating':'GroundService',
    'Avg_ServiceRating':'Service',
    'Avg_ValueRating':'Value',
    'Avg_WifiRating':'Wifi'
}

Updated_df = Main_data_df[list(columns_to_keep.keys())].rename(columns=columns_to_keep)
Updated_df.head(40)

,Airline,Overall,Comfort,Entertainment,Food,GroundService,Service,Value,Wifi
0,Southwest Airlines,9.00,4.00,0.00,3.00,4.00,5.00,5.00,0.00
1,Southwest Airlines,1.00,3.00,0.00,0.00,1.00,4.00,1.00,0.00
2,American Airlines,2.00,3.00,0.00,4.00,3.00,3.00,3.00,0.00
3,Southwest Airlines,3.00,1.00,1.00,1.00,1.00,4.00,1.00,1.00
4,Southwest Airlines,3.00,1.00,0.00,1.00,2.00,2.00,3.00,1.00
5,American Airlines,1.00,1.00,0.00,1.00,1.00,2.00,2.00,0.00
6,American Airlines,1.00,5.00,0.00,0.00,1.00,5.00,1.00,0.00
7,Southwest Airlines,1.00,5.00,0.00,5.00,1.00,5.00,1.00,0.00
8,United Airlines,1.00,1.00,1.00,1.00,5.00,2.00,1.00,1.00
9,American Airlines,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
10,American Airlines,1.00,3.00,4.00,3.00,1.00,4.00,1.00,4.00
11,Southwest Airlines,10.00,3.00,5.00,5.00,5.00,5.00,5.00,5.00
12,Spirit Airlines,3.00,3.00,1.00,1.00,1.00,4.00,1.00,1.00
13,Southwest Airlines,1.00,3.00,1.00,1.00,2.00,3.00,3.00,3.00
14,Spirit Airlines,1.00,1.00,0.50,0.75,1.00,1.00,1.00,0.50
15,United Airlines,1.00,2.00,1.00,1.00,2.00,1.00,1.00,0.00
16,Southwest Airlines,2.00,3.00,4.00,2.00,2.00,3.00,3.00,1.00
17,United Airlines,1.50,1.00,1.00,1.00,2.00,1.00,1.00,1.00
18,American Airlines,9.00,5.00,5.00,5.00,4.00,5.00,4.00,4.00
19,Spirit Airlines,1.33,1.67,0.33,0.33,2.33,3.00,1.33,1.33
20,American Airlines,3.00,2.00,3.00,1.00,1.00,3.00,1.00,0.00
21,Southwest Airlines,2.00,1.00,0.00,1.00,1.00,3.00,2.00,0.00
22,United Airlines,8.00,5.00,3.00,4.00,3.00,5.00,5.00,0.00
23,American Airlines,1.00,1.00,0.00,1.00,1.00,1.00,1.00,0.00
24,American Airlines,2.00,1.00,2.00,3.00,1.00,5.00,1.00,0.00
25,American Airlines,2.50,2.00,0.50,0.50,1.50,1.00,1.50,0.50
26,American Airlines,2.50,2.50,3.00,1.50,1.00,2.50,1.00,1.00
27,American Airlines,1.00,1.00,0.67,0.67,1.00,1.00,1.00,0.33
28,United Airlines,1.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00
29,Spirit Airlines,1.00,0.50,0.00,0.50,1.00,0.50,1.00,0.00
30,Southwest Airlines,10.00,3.00,5.00,5.00,5.00,5.00,5.00,5.00
31,American Airlines,7.00,5.00,3.00,3.00,5.00,5.00,4.00,0.00
32,Southwest Airlines,6.00,3.00,5.00,4.00,3.00,4.00,4.00,5.00
33,Frontier Airlines,1.00,1.00,1.00,1.00,1.00,2.00,2.00,1.00
34,United Airlines,1.00,1.00,1.00,0.67,1.00,0.67,1.00,0.67
35,Southwest Airlines,10.00,5.00,5.00,0.00,5.00,5.00,5.00,0.00
36,Spirit Airlines,1.00,0.50,0.00,0.50,1.00,0.50,2.00,0.00
37,American Airlines,1.00,5.00,3.00,4.00,1.00,3.00,1.00,3.00
38,Southwest Airlines,4.00,2.00,3.00,2.00,2.00,2.00,2.00,3.00
39,American Airlines,2.00,3.00,0.00,0.00,1.00,3.00,2.00,0.00

In [4]:
Airlines = Updated_df['Airline'].unique()
print(Airlines)

['Southwest Airlines' 'American Airlines' 'United Airlines'
 'Spirit Airlines' 'Frontier Airlines' 'Alaska Airlines' 'Allegiant Air']

In [5]:
# Group by 'Airline' and calculate the average scores
average_scores = Updated_df.groupby('Airline')[['Overall', 'Comfort','Entertainment', 'Food', 'GroundService', 'Service', 'Value', 'Wifi']].mean().reset_index()

# Display the resulting DataFrame
Average_df = pd.DataFrame(average_scores)
Average_df

,Airline,Overall,Comfort,Entertainment,Food,GroundService,Service,Value,Wifi
0,Alaska Airlines,3.292405,2.329530,1.191843,1.617166,2.037040,2.464237,2.101669,0.900204
1,Allegiant Air,2.587058,1.797453,0.465778,0.878314,1.748688,2.037201,1.882732,0.336778
2,American Airlines,2.552221,2.080536,1.239487,1.358872,1.757690,2.173533,1.762856,1.048759
3,Frontier Airlines,1.612408,1.338549,0.368121,0.594725,1.387918,1.612495,1.478943,0.306925
4,Southwest Airlines,3.987391,2.332986,1.142676,1.849633,2.344460,2.876655,2.499616,1.261041
5,Spirit Airlines,2.321832,1.551041,0.339730,0.683274,1.690798,1.993323,1.796427,0.303275
6,United Airlines,2.827921,2.097482,1.362340,1.432728,1.944135,2.385365,1.848703,1.193120

In [6]:
#Request User input for Airlines and Ratings to compare
print("Available airlines:", Airlines )
print("Available ratings: Overall, Comfort, Entertainment, Food, GroundService, Service, Value, Wifi")
selected_airlines = input("Pick 3 airlines to compare (separate with comma): ").split(',')
selected_ratings = input("Pick 3 ratings to compare (seperate with comma): ").split(',')

Available airlines: ['Southwest Airlines' 'American Airlines' 'United Airlines'
 'Spirit Airlines' 'Frontier Airlines' 'Alaska Airlines' 'Allegiant Air']
Available ratings: Overall, Comfort, Entertainment, Food, GroundService, Service, Value, Wifi

Pick 3 airlines to compare (separate with comma):  Southwest Airlines, United Airlines, Allegiant Air
Pick 3 ratings to compare (seperate with comma):  Overall, Comfort, Food

In [7]:
#Filter the data based on user selection
selected_airlines = [airline.strip() for airline in selected_airlines]
selected_ratings = [rating.strip() for rating in selected_ratings]

filtered_df = Average_df[Average_df['Airline'].isin(selected_airlines)][['Airline'] + selected_ratings]
filtered_df.set_index('Airline', inplace=True)
filtered_df

                     Overall   Comfort      Food
Airline
Allegiant Air       2.587058  1.797453  0.878314
Southwest Airlines  3.987391  2.332986  1.849633
United Airlines     2.827921  2.097482  1.432728

In [8]:
#Initiate the graph using Bokeh
source = ColumnDataSource(data={
    'Airline': filtered_df.index.tolist(),
    **{rating: filtered_df[rating].tolist() for rating in selected_ratings}
})

In [9]:
# Create the Bar Chart
p = figure(x_range=filtered_df.index.tolist(), y_range=(0, 6), title="Airline Ratings",
           height=400, toolbar_location=None, tools="")

colors = ["#00FF00", "#718dbf", "#e84d60"]
for i, rating in enumerate(selected_ratings):
    p.vbar(x=dodge('Airline', i * 0.25 - 0.25, range=p.x_range), top=rating, source=source,
           width=0.2, color=colors[i], legend_label=rating)

# Style the plot
p.xgrid.grid_line_color = None
p.legend.location = "top_left"
p.legend.orientation = "horizontal"
p.yaxis.axis_label = "Rating"

# Show the plot
show(p)